### ISSUE TITLE
TeamCity Error But not Local

### ISSUE THREAD

**Issue by ithielnor** [adamralph/stylecop-msbuild#6] opened 2016-07-25 20:20 UTC
4.7.54 is working fine on my local box, but the Teamcity agent is failing with

```
SA0001 : CoreParser : An exception occurred while parsing the file: System.IndexOutOfRangeException, Index was outside the bounds of the array.
   at StyleCop.CSharp.CodeLexer.GetOperatorSymbol(Char character)
   at StyleCop.CSharp.CodeLexer.GetSymbol(List`1 symbols, SourceCode sourceCode, Configuration configuration)
   at StyleCop.CSharp.CodeLexer.GetSymbols(SourceCode sourceCode, Configuration configuration)
   at StyleCop.CSharp.CodeParser.ParseDocument()
   at StyleCop.CSharp.CsParser.ParseFile(SourceCode sourceCode, Int32 passNumber, CodeDocument& document)
   at StyleCop.StyleCopThread.ParseAndAnalyzeDocument(SourceCode sourceCode, DocumentAnalysisStatus documentStatus)
   at StyleCop.StyleCopThread.DoWork(Object sender).
```

I was previously using 4.7.49.1 with no problem.

**Comment by adamralph** [comment] 2016-07-27 05:06
@ithielnor thanks for raising this.

Unfortunately nothing really springs to mind. I'm using 4.7.54 in several projects and it works just fine both locally and on TeamCity.

There's probably not much I can do without a reproduction of the issue, i.e. a solution/project which displays this problem.

It may also be worth raising this over at the [StyleCop project](https://stylecop.codeplex.com/) since it sounds like it may be something in the library itself rather than related to StyleCop.MSBuild. StyleCop.MSBuild is just a repackaging of StyleCop into a NuGet package.

**Comment by ithielnor** [comment] 2016-07-27 13:01
Thanks @adamralph. I'll submit an issue over there too. I'm not sure how to build a repro of this or I would

**Comment by adamralph** [comment] 2016-08-28 09:22
Closing this discussion. @ithielnor please comment and/or reopen if you still want to discuss anything here, but as I said I think the best place to pursue this is probably over at https://stylecop.codeplex.com/

**Closed as completed by adamralph** 2016-08-28 09:22 UTC
Labels: discussion
